name: audit-consumer

services:
  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - audit_consumer_network
    command: npm run start:dev

networks:
  audit_consumer_network:
    name: auth_api_network
    external: true
