name: audit-consumer

services:
  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    networks:
      - audit_consumer_network

networks:
  audit_consumer_network:
    name: auth_api_network
    external: true
